gradebook/urls.py
from django.urls import path, include
from django.contrib import admin
from .views import gradebook, student, teacher, ed_admin


urlpatterns = [ 
    path('', gradebook.HomePageView.as_view(), name='homepage'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', gradebook.SignUpView.as_view(), name='signup'), #general signup to set user role
    path('accounts/profile/', gradebook.profile, name='profile'),  #url for login_redirect

    path('student/', include(([
        path('signup/', student.signup, name='signup'),
        path('<slug:slug>', student.StudentMainView.as_view(), name='main'),
    ], 'gradebook'), namespace = 'student')),


    path('teacher/signup/', teacher.signup, name='teacher_signup'),
    path('teacher/<slug:slug>/', teacher.TeacherMainView.as_view(), name='teacher_main'),
    path('teacher/<slug:slug>/', include(([
        path('course/add/', teacher.course_add, name='course_add'),
        path('subject/add/', teacher.SubjectAddView.as_view(), name='subject_add'),
        path('subject/<int:pk>/update/', teacher.subject_update, name='subject_update'),
        path('subject/<int:pk>/delete/', teacher.subject_delete, name='subject_delete'),
        path('subject/<int:subject_pk>/course/<int:course_pk>/update/', teacher.course_update, name='course_update'),
        path('subject/<int:subject_pk>/course/<int:course_pk>/delete/', teacher.course_delete, name='course_delete'),
        path('course/<int:course_pk>/students/edit/', teacher.student_edit, name='student_edit'),
        path('course/<int:course_pk>/student/<int:student_pk>/delete/', teacher.student_delete, name='student_delete'),
        path('subject/<int:subject_pk>/course/<int:course_pk>/gradebook/', teacher.gradebook, name='gradebook'),
    ], 'gradebook'), namespace = 'teacher')),
]


#     path('teacher/', include(([
#         path('signup/', teacher.signup, name='signup'),
#         path('<slug:slug>', teacher.TeacherMainView.as_view(), name='main'),
#         path('course/add/', teacher.course_add, name='course_add'),
#         path('subject/add/', teacher.SubjectAddView.as_view(), name='subject_add'),
#         path('subject/<int:pk>/update/', teacher.subject_update, name='subject_update'),
#         path('subject/<int:pk>/delete/', teacher.subject_delete, name='subject_delete'),
#         path('subject/<int:subject_pk>/course/<int:course_pk>/update/', teacher.course_update, name='course_update'),
#         path('subject/<int:subject_pk>/course/<int:course_pk>/delete/', teacher.course_delete, name='course_delete'),
#         path('course/<int:course_pk>/students/edit/', teacher.student_edit, name='student_edit'),
#         path('course/<int:course_pk>/student/<int:student_pk>/delete', teacher.student_delete, name='student_delete'),
#         path('subject/<int:subject_pk>/course/<int:course_pk>/gradebook/', teacher.gradebook, name='gradebook')
#     ], 'gradebook'), namespace = 'teacher')),
# ]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.conf import settings



urlpatterns = [
    path('', include('gradebook.urls')),
    path('admin/', admin.site.urls),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
]

gradebook/views/gradebook.py
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls.base import reverse_lazy, reverse
from django.views.generic.base import TemplateView
from django.contrib import messages
from gradebook.models import User

class HomePageView(TemplateView):
    template_name = 'gradebook/homepage.html'

class SignUpView(TemplateView):
    template_name = 'registration/signup.html'

@login_required
def profile(request):
    if request.user.role == User.STUDENT:
        return HttpResponseRedirect(reverse('student:main', args=[request.user.slug]))
    elif request.user.role == User.TEACHER:
        return HttpResponseRedirect(reverse('teacher_main', args=[request.user.slug]))
    else:
        return HttpResponseRedirect('homepage')

gradebook/views/student.py
from django.template.defaultfilters import slugify
from django.views.generic.edit import CreateView
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import DetailView, ListView, TemplateView
from gradebook.forms import RegistrationForm, CourseForm
from django.contrib import messages
from gradebook.models import Course, Faculty, User
from django.urls import reverse_lazy, reverse
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin


def signup(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        form_course = CourseForm(request.POST)

        if form.is_valid() and form_course.is_valid():
            course = form_course.save(commit=False)

            year = form_course.cleaned_data['year']
            group = form_course.cleaned_data['group']
            faculty = form_course.cleaned_data['faculty']

            if Course.objects.filter(year=year, group=group, faculty=faculty).exists():
                course = Course.objects.get(year=year, group=group, faculty=faculty)
            else:
                course = Course.objects.create(year=year, group=group, faculty=faculty)

            user = form.save(commit=False)
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            user.slug = slugify(f'{first_name, last_name}') 
            user.course = course
            user.save()

            form.save_m2m()
            form_course.save_m2m()

            email = form.cleaned_data['email']
            password = form.cleaned_data['password1']
            user = authenticate(email=email, password=password)
            login(request, user)

            return redirect(reverse('student:main', args=[request.user.slug]))
    else:
        form = RegistrationForm()
        form_course = CourseForm()

    return render(request, 'registration/student_signup.html', {'form': form, 'form_course': form_course})


class StudentMainView(LoginRequiredMixin, TemplateView):
    template_name = 'gradebook/student/main.html'

gradebook/views/teacher.py
from django.contrib.auth import login, authenticate
from django.forms.formsets import BaseFormSet, formset_factory
from django.http import HttpRequest
from django.http.response import HttpResponse
from django.forms import modelformset_factory, formset_factory
from django.urls import reverse
from django.views.generic import View, ListView, DetailView, TemplateView, UpdateView, CreateView
from django.views.generic.edit import DeleteView, FormView
from gradebook.forms import TaskForm, RegistrationForm, SubjectForm, TeacherCourseForm, CourseForm, GradeForm
from gradebook.models import Task, Course, Subject, User, Gradebook
from django.shortcuts import get_list_or_404, get_object_or_404, render, redirect
from django.template.defaultfilters import slugify
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required



def signup(request):
    if request.method == 'POST': 
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.role = User.TEACHER
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            user.slug = slugify(f'{first_name, last_name}')
            user.save()

            email = form.cleaned_data['email']
            password = form.cleaned_data['password1']
            user = authenticate(email=email, password=password)
            login(request, user)
        return redirect(reverse('teacher_main', args=[request.user.slug]))

    else:
        form = RegistrationForm()
    return render(request, 'registration/teacher_signup.html', {'form': form})

class TeacherMainView(LoginRequiredMixin, ListView):
    template_name = 'gradebook/teacher/main.html'
    def get_queryset(self):
        teacher = get_object_or_404(User, id=self.request.user.id)
        subject_ids = Gradebook.objects.filter(teacher=teacher).values('subject_id')
        queryset = Subject.objects.filter(id__in=subject_ids).order_by('title')
        return queryset

class SubjectAddView(LoginRequiredMixin, FormView):
    template_name = 'gradebook/teacher/subject_form.html'
    form_class = SubjectForm
    def get_success_url(self):
        return reverse('teacher_main', args=[self.request.user.slug])
    def form_valid(self, form):
        subject = Subject.objects.get_or_create(title=form.cleaned_data['title'])[0]
        teacher = get_object_or_404(User, id=self.request.user.id)
        Gradebook.objects.get_or_create(teacher=teacher, subject=subject)
        return super().form_valid(form)

@login_required
def subject_update(request, pk, **kwargs):
    subject = get_object_or_404(Subject, pk=pk)
    teacher = get_object_or_404(User, id=request.user.id)
    if request.method == 'POST':
        form = SubjectForm(request.POST, instance=subject)
        if form.is_valid():
            new_subject = Subject.objects.get_or_create(title=form.cleaned_data['title'])[0]
            
            Gradebook.objects.filter(subject=subject, teacher=teacher).update(subject=new_subject)

        return redirect(reverse('teacher_main', args=[request.user.slug]))
    else:
        form = SubjectForm(instance=subject)
    return render(request, 'gradebook/teacher/subject_form.html', {'form': form})


@login_required
def subject_delete(request, pk, **kwargs):
    subject = get_object_or_404(Subject, pk=pk)
    teacher = get_object_or_404(User, id=request.user.id)
    if request.method == 'POST':
        Gradebook.objects.filter(subject=subject, teacher=teacher).delete()
        return redirect(reverse('teacher_main', args=[request.user.slug]))
    return render(request, 'gradebook/teacher/subject_confirm_delete.html', {'subject': subject})


@login_required
def course_add(request, **kwargs):
    teacher = get_object_or_404(User, id=request.user.id)
    if request.method == "POST":
        form = TeacherCourseForm(request.user, request.POST)
        if form.is_valid():
            course = form.save(commit=False)
            course = Course.objects.get_or_create(
                year=form.cleaned_data['year'],
                group=form.cleaned_data['group'],
                faculty=form.cleaned_data['faculty'],
            )[0]
            subject = Subject.objects.get(title=form.cleaned_data['subject'])

            Gradebook.objects.update_or_create(
                teacher=teacher, subject=subject, course=None,
                defaults={'course':course},
            )
            form.save_m2m()     
        return redirect(reverse('teacher_main', args=[request.user.slug]))
    else:
        form = TeacherCourseForm(request.user)
    return render(request, 'gradebook/teacher/course_form.html', {'form': form})

@login_required
def course_update(request, subject_pk, course_pk, **kwargs):
    course = get_object_or_404(Course, pk=course_pk)
    subject = get_object_or_404(Subject, pk=subject_pk)
    teacher = get_object_or_404(User, id=request.user.id)
    if request.method == 'POST':
        form = CourseForm(request.POST, instance=course)
        if form.is_valid():
            new_course = Course.objects.get_or_create(
                faculty=form.cleaned_data['faculty'],
                year = form.cleaned_data['year'],
                group = form.cleaned_data['group'],
                )[0]
            
            Gradebook.objects.filter(course=course, subject=subject, teacher=teacher).update(course=new_course)
        return redirect(reverse('teacher_main', args=[request.user.slug]))
    else:
        form = CourseForm(instance=course)
    return render(request, 'gradebook/teacher/course_update.html', {'form': form, 'subject': subject})

@login_required
def course_delete(request, subject_pk, course_pk, **kwargs):
    course = get_object_or_404(Course, pk=course_pk)
    subject = get_object_or_404(Subject, pk=subject_pk)
    teacher = get_object_or_404(User, id=request.user.id)
    
    if request.method == 'POST':
        Gradebook.objects.filter(course=course, subject=subject, teacher=teacher).delete()
        return redirect(reverse('teacher_main', args=[request.user.slug]))
    return render(request, 'gradebook/teacher/course_confirm_delete.html', {'course': course, 'subject': subject})


# class StudentListView(LoginRequiredMixin, View):
#     template_name = 'gradebook/teacher/student_list.html'
#     def get(self, request, course_pk):
#         course = get_object_or_404(Course, pk=course_pk)
#         student_list = User.objects.filter(course=course).order_by('last_name')
#         return render(request, self.template_name, {'student_list': student_list, 'course': course})

@login_required
def student_edit(request, course_pk, **kwargs):
    StudentFormSet = modelformset_factory(User, fields=('first_name', 'last_name', 'email'), extra=10,) 
    course = get_object_or_404(Course, pk=course_pk)
    
    if request.method == 'POST':
        formset = StudentFormSet(request.POST, queryset=User.objects.filter(course=course_pk))
        if formset.is_valid():
            students = formset.save(commit=False)
            for student in students:
                student.course = course
                first_name = student.first_name
                last_name = student.last_name
                student.slug = slugify(f'{first_name, last_name}')
                student.save()
                Gradebook.objects.create(course=course, student=student)

            return redirect(reverse('teacher:student_edit', kwargs={'slug': request.user.slug, 'course_pk': course_pk}))
    else:
        formset = StudentFormSet(queryset=User.objects.filter(course=course))
    return render(request,'gradebook/teacher/student_formset.html', {'formset': formset, 'course': course})

@login_required
def student_delete(request, course_pk, student_pk, **kwargs):
    course = get_object_or_404(Course, pk=course_pk)
    student = get_object_or_404(User, pk=student_pk)
    if request.method == 'POST':
        User.objects.filter(course=course, pk=student_pk).delete()
        return redirect(reverse('teacher:student_edit', kwargs={'slug': request.user.slug, 'course_pk': course_pk}))
    context = {'course':course, 'student': student}
    return render(request, 'gradebook/teacher/student_confirm_delete.html', context)



@login_required
def gradebook(request, subject_pk, course_pk, **kwargs):
    course = get_object_or_404(Course, pk=course_pk)
    subject = get_object_or_404(Subject, pk=subject_pk)
    teacher = get_object_or_404(User, pk=request.user.id)
    student_list = User.objects.filter(course=course).order_by('last_name')
    tasks_ids = Gradebook.objects.filter(course=course, subject=subject).values('task_id')
    task_list = Task.objects.filter(id__in=tasks_ids)

    task_form=TaskForm()
    GradeFormSet = modelformset_factory(Gradebook, fields=(
        'grade', 'student', 'task',), max_num=len(student_list), extra=7,
    )

    if request.method == 'POST':

        if 'add_task' in request.POST:
            task_form = TaskForm(request.POST)
            if task_form.is_valid():
                task = task_form.save(commit=False)
                task.save()
                
                Gradebook.objects.update_or_create(
                    course=course, subject=subject, teacher=teacher, task=None,
                    defaults={'task': task},
                )

            return redirect(reverse('teacher:gradebook', 
                    kwargs={'slug': request.user.slug, 'subject_pk': subject_pk, 'course_pk': course_pk})
                )

        elif 'add_grade' in request.POST:
            grade_formset = GradeFormSet(request.POST, queryset=None)
            if grade_formset.is_valid():
                formset = grade_formset.save(commit=False)
                for form in formset:

                    stud_record = Gradebook.objects.filter(
                        course=course, subject=subject, teacher=teacher, task=form.task, student=form.student)

gradebook/templates/gradebook/teacher/course_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<form method="POST">
{% csrf_token %}

<h1> Are you sure you want to delete {{course}} from your subject {{subject}}? </h1>
<p> You will lose all your records related to this course and subject. </p>
<input type="submit" value="Yes, delete">

</form>
{% endblock %}

gradebook/templates/gradebook/teacher/course_form.html
{% extends "base.html" %}

{% block content %}

<h1> Add courses you are teaching  </h1>


<form method="POST">
{% csrf_token %}

{{form.as_p}}

<button type="submit">Submit</button>

<p> <a href="{% url 'teacher:subject_add' user.slug %}"> Add subject </a> </p>

</form>
{% endblock %}

gradebook/templates/gradebook/teacher/course_update.html
{% extends "base.html" %}

{% block content %}

<h1> Update course for {{subject}} </h1>


<form method="POST">
{% csrf_token %}

{{form.as_p}}

<button type="submit">Submit</button>

<p> <a href="{% url 'teacher:subject_add' user.slug %}"> Add subject </a> </p>

</form>
{% endblock %}

gradebook/templates/gradebook/teacher/gradebook_table.html
{% extends "base.html" %}

{% block content %}


<style type="text/css">
    table {
      border-collapse: collapse;
    }
    th, td {
        border: 1px solid black;
        padding: 5px;
    }
</style>

<h1> Students' grades </h1>
<h2> Class: {{course}} </h2>
<h2> Subject: {{subject}} </h2>


<form method="POST">
    {% csrf_token %}
    {{ task_form }}
<input type="submit" name="add_task" value = "Add"/>
</form>

<br>

<form method="POST">
    {% csrf_token %}

    {{ formset.management_form }}

    
    <table> 


        <tr>
            <th> № </th>
            <th> Student </th>
            {% for task in task_list %}
            <th> {{task}} </th>
            {% endfor %}
        </tr>
        


        {% for student in student_list %}

        <tr> 
            <td> {{ forloop.counter }}. </td>
            
            <td> {{ student}} </td>


            {% for i in task_list %}
                <td> {{form.grade}}</td>
            {% endfor %}
        </tr>
        {% endfor %}

     
    </table>


<br>
<input type="submit" name="add_grade" value = "Save"/>
</form> 

<p> <a href="{% url 'teacher:student_edit' user.slug course.id %}"> Add or edit student list in class: {{course}} </a> </p> 

{% endblock %}

gradebook/templates/gradebook/teacher/main.html
{% extends "base.html" %}

{% block content %}

<h1> Hi teacher {{user.first_name}} {{user.last_name}} </h1>

<p> Your subjects and classes </p>

{% if subject_list %}
<ul>
    {% for subject in subject_list %}
        <li> {{subject}} | <a href="{{user.get_absolute_url}}{{subject.get_absolute_url}}update"> Update </a>
            | <a href="{{user.get_absolute_url}}{{subject.get_absolute_url}}delete"> Delete </a> </li>
            <ul>
                {% for course in subject.courses_of_subject %}
                    <li> {{course}} | 
                        <a href="{{user.get_absolute_url}}{{subject.get_absolute_url}}{{course.get_absolute_url}}update"> Update </a>
                    | <a href="{{user.get_absolute_url}}{{subject.get_absolute_url}}{{course.get_absolute_url}}delete"> Delete </a> 
                    <br> <a href="{{user.get_absolute_url}}{{subject.get_absolute_url}}{{course.get_absolute_url}}gradebook">
                        Go to a Gradebook </a>
                </li>
                {% endfor %} 
            </ul>
            <br>

    {% endfor %}
</ul>

{% else %}
    <p> Please add subjects and classes you are teaching to get started </p>

{% endif %}


<p> <a href="{% url 'teacher:subject_add' user.slug %}"> Add subjects </a>  </p>

<p> <a href="{% url 'teacher:course_add' user.slug %}"> Add classes </a>  </p>


{% endblock %}

gradebook/templates/gradebook/teacher/student_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<form method="POST">
{% csrf_token %}

<h1> Are you sure you want to delete {{student}} from class: {{course}}? </h1>
<p> You will lose all your records related to this student. </p>
<input type="submit" value="Yes, delete">

</form>
{% endblock %}

gradebook/templates/gradebook/teacher/student_formset.html
{% extends "base.html" %}

{% block content %}

<h1> Edit student list in class {{course}} </h1>

<form method="POST">

{% csrf_token %}
{{ formset.management_form }}
{% for form in formset %}
    <div class="form-group">
    {% if form.instance.id %}
        <p> {{form}} <a href="{{user.get_absolute_url}}{{course.get_absolute_url}}student/{{form.instance.id}}/delete"> Delete </a> {{form.instance.id }} </p>
    {% else %}
        <p> {{form}}
    </div> 
    {% endif %}
{% endfor %}



<input type="submit" value="Save">

</form>
{% endblock %}

gradebook/templates/gradebook/teacher/subject_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<form method="POST">
{% csrf_token %}

<h1> Are you sure you want to delete {{subject}} from your subjects? </h1>
<p> You will lose all your records related to {{subject}}. </p>
<input type="submit" value="Yes, delete">

</form>
{% endblock %}

gradebook/templates/gradebook/teacher/subject_form.html
{% extends "base.html" %}

{% block content %}

<h1> Add subjects you are teaching </h1>

<form method="POST">
{% csrf_token %}
{{form.as_p}}


<button type='submit'>Submit</button>


<p> <a href="{% url 'teacher:course_add' user.slug %}"> Add class you are teaching </a> </p>

</form>
{% endblock %}